---
# tasks file for zookeeper
######## Install Java ########
- name: Install Java on RedHat
  block:
    - name: Copy rmp Liberica JDK
      ansible.builtin.get_url:
        dest: /tmp
        url: https://download.bell-sw.com/java/17.0.6+10/bellsoft-jdk17.0.6+10-linux-amd64.rpm
        mode: "755"

    - name: Install java (Liberica JDK https://bell-sw.com/pages/downloads/)
      ansible.builtin.dnf:
        name: /tmp/bellsoft-jdk17.0.6+10-linux-amd64.rpm
        state: present
        disable_gpg_check: true

  when: ansible_facts['os_family'] == 'RedHat'


- name: Install Java on Ubuntu
  block:
    - name: Copy rmp Liberica JDK
      ansible.builtin.get_url:
        dest: /tmp
        url: https://download.bell-sw.com/java/17.0.6+10/bellsoft-jdk17.0.6+10-linux-amd64.deb
        mode: "755"

    - name: Install java (Liberica JDK https://bell-sw.com/pages/downloads/)
      ansible.builtin.apt:
        deb: /tmp/bellsoft-jdk17.0.6+10-linux-amd64.deb

  when: ansible_facts['os_family'] == 'Debian'

######## Install and config zookeeper ########
- name: Add the user 'zookeeper' for zookeeper
  ansible.builtin.user:
    name: zookeeper
    create_home: no
    shell: /bin/bash
    groups: "adm"

- name: Download zookeeper bin
  ansible.builtin.get_url:
    dest: /tmp
    url: https://dlcdn.apache.org/zookeeper/zookeeper-3.8.1/apache-zookeeper-3.8.1-bin.tar.gz
    mode: "755"

- name: Extract zookeeper source into /opt/zookeeper
  ansible.builtin.unarchive:
    src: /tmp/apache-zookeeper-3.8.1-bin.tar.gz
    remote_src: yes
    dest: /opt
    owner: zookeeper
    group: zookeeper

- name: Create a symbolic link to latest zookeeper directory
  ansible.builtin.file:
    src: /opt/apache-zookeeper-3.8.1-bin
    dest: /opt/zookeeper
    owner: zookeeper
    group: zookeeper
    state: link

- name: Copy zookeeper config
  ansible.builtin.template:
    dest: /opt/zookeeper/conf/zoo.cfg
    src: conf/zoo.cfg.j2
    owner: zookeeper
    group: zookeeper

- name: Create directory for data zookeeper
  ansible.builtin.file:
    path: /var/lib/zookeeper
    state: directory
    owner: zookeeper
    group: zookeeper

- name: Copy zookeeper myid
  ansible.builtin.template:
    dest: /var/lib/zookeeper/myid
    src: conf/myid.j2
    owner: zookeeper
    group: zookeeper

- name: Creating and Using a Systemd Unit File
  ansible.builtin.template:
    dest: /etc/systemd/system/zookeeper.service
    src: unit/zk.service.j2
    owner: zookeeper
    group: zookeeper

- name: Make sure a service zookeeper unit is running
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: zookeeper
